### ISSUE TITLE
Multiple toggles

### ISSUE THREAD

**Issue by joeabill** [gfazioli/react-toggle#1]
Thanks for the great plugin!

I noticed that if you have multiple toggles on the same page, only the first one works. I had to define a unique "id" for it to work. I think it would be good to mention this in the docs.

Also, the docs say the onToggle event should have an "event" property but I'm only getting the "checked" property. Not a big deal as I found a workaround but just thought I would mention that.

**Comment by djrokita** [comment]
I had problem with multiple toggles too, but using "name" property works as well.

**Comment by gfazioli** [comment]
@joeabill @djrokita updated docs for unique `name` with multiple toggles.

@joeabill I checked and for me, the event object works fine

```js
<Toggle onToggle={(value,event) => { console.log(value,event) } } />
```

could check again?
