### ISSUE TITLE
Can we get two-way binding for checked attribute?

### ISSUE THREAD

**Issue by taylorj91** [gfazioli/react-toggle#10]
Two-way binding would be nice for checked. Expected functionality would be if I set the 'checked' value to a state variable, and that variable is changed, the toggle would update to reflect this new state change.

Currently I don't see this functionality implemented anywhere.

My workaround includes onStateChange doing the following:
document.getElementById('myToggler').checked = togglerCheckedVal

Thanks!

**Comment by gfazioli** [comment]
@taylorj91 didn't get the point... could you provide with me more details...

**Comment by gfazioli** [comment]
@taylorj91 you can do that by using 


```
const isChecked = true;
...

<label htmlFor="toggle-2">
  <Toggle name="toggle-2" checked={isChecked} />
  Right label
</label> 
```

When `isChecked` changes, you'll see the update

**Comment by nickvonh** [comment]
The component does not update, when an external `checked` source is changed.
