### ISSUE TITLE
Move styled-components as a peerDependency

### ISSUE THREAD

**Issue by lcospain** [gfazioli/react-toggle#13]
**Describe the bug**
Hello, and thank you for this great component. I wanted to use your library as part of a project that depends on styled-components and saw some warnings after installation regarding styled-components being instantiated twice.

**To Reproduce**
1. Create a folder `mkdir repro`
2. Init npm package `npm init -y`
3. Install styled-components `npm i styled-components`
4. Install react-toggle-component `npm i react-toggle-component`
5. After bundling, the console should show the warning available in screenshots

**Expected behavior**
Styled-components should be put in [peerDependencies](https://github.com/gfazioli/react-toggle/blob/master/package.json#L52)

**Screenshots**
Warning message printed to the console :
![Warning message](https://i.ibb.co/HXwmQNS/sc-twice.png)

**Desktop (please complete the following information):**
 - OS: Mac Os
 - Browser: Google Chrome
 - Version: 74

**Additional context**

**Comment by gfazioli** [comment]
@lcospain Hi, interesting, I'll check soon, thx 👍

**Comment by gfazioli** [comment]
should be ok on `v3.0.6`
