### ISSUE TITLE
build in 'prepare' script

### ISSUE THREAD

**Issue by adrian-delgado** [gfazioli/react-toggle#14]
**Is your feature request related to a problem? Please describe.**
It would be nice to not require typescript installed globally when `yarn add`/`npm install`ing this package.

**Describe the solution you'd like**
running `tsc -p tsconfig.json` in the `prepare` script instead of the `postinstall` should have access to the node_modules folder. Also including typescript (or tsc) as a dev dependency will be required. This way the `tsc` command will reference typescript from the node_modules folder.

**Describe alternatives you've considered**
none

**Additional context**
sorry if this has been tried before, but I suppose there has to be a way to not require the consuming project to have global node modules installed.

**Comment by djorg83** [comment]
I agree with the above ^ request.  You should generally avoid publishing files that need to be compiled/transpiled in order for the package to be used.  Please consider compiling your typescript into a /dist folder, then only publish the contents of the /dist folder to npm.  This can be accomplished via .npmignore and/or the package.json "files" attribute.

**Comment by rolandpeelen** [comment]
I agree to both these, my build pipeline breaks too. Here is a PR to the proposed solution: https://github.com/gfazioli/react-toggle/pull/19
