### ISSUE TITLE
bug? Initial value is stucked on true

### ISSUE THREAD

**Issue by sinodko** [gfazioli/react-toggle#16]
Initial value set to true is not working. It is always false on first render.

even with this code:

    <Toggle
            backgroundColor={themeContext.backgroundColor}
            borderColor={themeContext.textColor}
            knobColor={themeContext.textColor}
            name="toggle-3"
            value={true}
            onToggle={handleSetTheme}
          />

the result is:

<img width="139" alt="Screenshot 2019-07-23 at 08 57 48" src="https://user-images.githubusercontent.com/33039909/61689699-f529d500-ad27-11e9-94d3-401d82bc891b.png">

**Comment by sinodko** [comment]
ok definitely my bad.. I'm sorry. If anyone also encounters this problem just add `checked` prop!

    <Toggle
        backgroundColor={themeContext.backgroundColor}
        borderColor={themeContext.textColor}
        knobColor={themeContext.textColor}
        checked={themeValue}
        name="toggle-3"
        value={true}
        onToggle={handleSetTheme}
      />

**Comment by gfazioli** [comment]
@sinodko yes, exactly, no problem. The `value` is the value send in POST when you're using the toggle inside a form. Actually, it is not used to set the toggle status but it is used as a value, for example:

```jsx
<form method="post">
  <label>Addition ram</label>
  <Toggle value="ram" name="additional_ram" />

  <label>Sizie</label>
  <Toggle value="large" name="size" />

  <button>Send</button>
</form>
``` 
In the above example you'll receive `additional_ram` and `size` only when the toggle is *on* ;)
