### ISSUE TITLE
Addition of an extra state so that it behaves as a tri state switch

### ISSUE THREAD

**Issue by vjr12** [gfazioli/react-toggle#17]
Want to implement something like a switch that has three states, "ENABLED,PENDING,DISABLED" . Is it possible that something like this can be implemented

Something like this?
![Screenshot from 2019-08-13 17-14-01](https://user-images.githubusercontent.com/42905121/62939069-037e8480-bdee-11e9-8ca4-28d3df4ec6d7.png)

![Screenshot from 2019-08-13 17-16-48](https://user-images.githubusercontent.com/42905121/62939143-332d8c80-bdee-11e9-84a7-ea3594eb23e5.png)

![Screenshot from 2019-08-13 17-16-35](https://user-images.githubusercontent.com/42905121/62939174-404a7b80-bdee-11e9-8cbf-a724020b4571.png)

**Comment by gfazioli** [comment]
the toggle should be a boolean, 0 || 1, false || true. Anyway, you could use the disable to underline that the state (0 || 1) is indeterminate, something like

```
[O   ]        // false

[O   ]       // on the click, set the disabled = true

[   O]       // changing
```

**Comment by velsonjr** [comment]
@gfazioli Would you help me by editing this sandbox, https://codesandbox.io/s/react-toggle-39ej9?

**Comment by gfazioli** [comment]
something like that 

```jsx
import React from "react";
import ReactDOM from "react-dom";
import { Toggle } from "react-toggle-component";

import styled from "styled-components";

const Label = styled.label`
  font-weight: bold;
  display: grid;
  grid-auto-flow: column;
  grid-auto-columns: min-content;
  white-space: nowrap;
  align-items: center;
  cursor: pointer;
`;

const Sample = styled.div`
  padding: 16px;
`;

const Root = styled.div`
  font-family: Arial, Helvetica, sans-serif;
  h1 {
    text-align: center;
  }

  h2 {
    padding-bottom: 4px;
    border-bottom: 1px solid #ccc;
  }
`;

class App extends React.Component {

  state = {
    loading : false,
    checked : false,
  }

  onToggle(event) {
    const {checked} = event.target

    this.setState({loading: true})   

    // do something
    setTimeout(
      () => {
        this.setState({loading: false, checked})   
      }, 2000
    )
  }

  render() {
    return (
      <Root>
        <Sample>
          <Label htmlFor="toggle-3">
            <Toggle
              leftBackgroundColor={this.state.loading ?"#eee":"blue"}
              rightBackgroundColor={this.state.loading ?"#eee":"green"}
              backgroundColorDisabled="white"
              borderColor="black"
              knobColor="white"
              name="toggle-3"
              checked={this.state.checked}
              controlled={true}
              disabled={this.state.loading}
              onToggle={this.onToggle.bind(this)}
            />
          </Label>
        </Sample>
      </Root>
    );
  }
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**Comment by velsonjr** [comment]
@gfazioli Thanks much! But still it has dual state. I would want something that should indicate a partial selection. Like three states, slider should be on left (enabled), in the center(partial) and to the right(disabled). Hope you understood this:)

**Comment by gfazioli** [comment]
maybe, you need a different component for that 🤔 anyway, I'll think about that
