### ISSUE TITLE
Add posibility to style the knob itself.

### ISSUE THREAD

**Issue by padsbanger** [gfazioli/react-toggle#22]
**Is your feature request related to a problem? Please describe.**
I would like to have an ability to style the knob itself.

**Describe the solution you'd like**
An ability to pass styles to knob so that I can style it like this: 
![1](https://user-images.githubusercontent.com/471029/79444534-930eaf80-7fdb-11ea-8bf0-4f3a4c9666fe.png)

(white background with black border)

**Comment by gfazioli** [comment]
@padsbanger hey, if you are using the styled-components, you may

```ts
const Wire = styled(Toggle)`
  && {
    input[type="checkbox"] + label::after {
      border:2px solid #000;
      width: 14px;
      height: 14px;
    }
  }  
`
```

and then 

```ts
     <Label htmlFor="toggle-9">
            <Wire
              leftBackgroundColor="white"
              rightBackgroundColor="white"
              borderColor="black"
              knobColor="white"
              name="toggle-9"
              onToggle={e => console.log("onToggle", e.target.checked)}
            />
            Right label
   </Label>
```

![image](https://user-images.githubusercontent.com/432181/85519041-2fb78400-b601-11ea-9873-ee8842a54601.png)
