### ISSUE TITLE
react-controlled-component warning

### ISSUE THREAD

**Issue by MichaelLiss** [gfazioli/react-toggle#4]
The component looks very nice.  Thank you.
I installed it, coded it up and got this warning:
I like to remove all warnings from my code before I release, if you can help with this :-) that would be awesome 

Warning: A component is changing an uncontrolled input of type checkbox to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. 
More info: https://fb.me/react-controlled-components

Here is my code:

    import Toggle from "react-toggle-component"
    import "react-toggle-component/styles.css" 

I use the toggle like this: (other code removed for clarity)

     render() {
        const { user } = this.props.auth;

        let Content = null;

        if (user === null ) {
          Content = <Spinner />;
        } else {

          let engineSwitch = null;
          if( user.role === 'admin'){
            engineSwitch = (
              <Toggle label="Off" labelRight="On" />
            )
          }
        
          Content = (
            <div>
              {engineSwitch}
            </div>
          );      
      }

        return (
          <div className="dashboard">
            <div className="container">
              <div className="row">
                <div className="col-md-12">
                  <h3 className="display-4">Engine</h3>
                  {Content}
                </div>
              </div>
            </div>
          </div>
        );
      }
    }

**Comment by gfazioli** [comment]
@MichaelLiss I think that the issue is due to `onChange()` event handler miss in your code, try with

```jsx
<Toggle label="Off" labelRight="On" onToggle={(checked,evt) => console.log("onToggle", checked, evt)} />
```

**Comment by gfazioli** [comment]
@MichaelLiss I'll try to use a different approach for render

```jsx
  render() {
    const { user } = this.props.auth;

    function Content() {
      if (!user) {
        return <Spinner />;
      }

      if (user.role !== 'admin') {
        return null;
      }

      return <Toggle label="Off" labelRight="On" onToggle={(checked, evt) => console.log("onToggle",checked,evt)}/>
    }

    return (
      <div className="dashboard">
        <div className="container">
          <div className="row">
            <div className="col-md-12">
              <h3 className="display-4">Engine</h3>
              <Content />
            </div>
          </div>
        </div>
      </div>
    );
  }
```

**Comment by MichaelLiss** [comment]
thanks !  Works !  much appreciated

**Comment by gfazioli** [comment]
@MichaelLiss you're welcome 👍
