### ISSUE TITLE
multiple toggles in same app do not function independently

### ISSUE THREAD

**Issue by MichaelLiss** [gfazioli/react-toggle#5]
Hi,

the toggle control is pretty cool... when I use two of them in the same app however, the second one controls the first

Screen shot before:

![image](https://user-images.githubusercontent.com/39492750/53663908-deb99a80-3c1b-11e9-8b58-606d593ada1d.png)

Screen shot **after clicking on second toggle** (Hide previous days2), notice first toggle slides to left as if it had been clicked.
I expected the second toggle to slide to the left.

![image](https://user-images.githubusercontent.com/39492750/53663935-f133d400-3c1b-11e9-862a-b54ae3557e93.png)

Here is the relevant code:

Constructor setup:

    constructor( props )
    {
      super( props );

      this.state = {
        hidePastDays:true,
        hidePastDays2:true,
        errors:null,
      }
    } 

"toggle" handlers:

    onToggle(value) {
        this.setState( {hidePastDays: value} );
    }

    onToggle2(value) {
      this.setState( {hidePastDays2: value} );
    }

render function:

         let hideSwitch = null;
         let hideSwitch2 = null;

          hideSwitch = (
            <div className="row">
              <Toggle 
                checked={this.state.hidePastDays}
                onToggle={(value) => { this.onToggle(value) } }
              />
              <p>Hide previous days</p>
            </div>
          );

          hideSwitch2 = (
            <div className="row">
              <Toggle 
                checked={this.state.hidePastDays2}
                onToggle={(value) => { this.onToggle2(value) } }
              />
              <p>Hide previous days2</p>
            </div>
          );

    return (
        <div>
          {hideSwitch}
          {hideSwitch2}
        </div>
    );

**Comment by gfazioli** [comment]
@MichaelLiss since they are the form component, you have to use the `name` props

```jsx
    return (
      <div>
        <div>
          <Toggle
            name="toggle-1"
            label="Off"
            labelRight="On"
            onToggle={(checked, evt) => console.log("onToggle", checked, evt)}
          />
        </div>

        <div>
          <Toggle
            name="toggle-2"
            label="Off"
            labelRight="On"
            onToggle={(checked, evt) => console.log("onToggle", checked, evt)}
          />
        </div>

      </div>
    );
```

**Comment by MichaelLiss** [comment]
ahhh...  OK .. thanks
