### ISSUE TITLE
Incorrect suggested usage of component

### ISSUE THREAD

**Issue by taylorj91** [gfazioli/react-toggle#7]
Instead of importing Toggle, I had to change my import to:
import {Toggle} from "react-toggle-component".

Otherwise I would get the following error:
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by gfazioli** [comment]
@taylorj91 yep, I updated the doc, this because https://basarat.gitbooks.io/typescript/docs/tips/defaultIsBad.html
